[package]
name = "yaai-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
grep-regex = "0.1"
grep-searcher = "0.1"
ignore = "0.4"

[dev-dependencies]
tempfile = "3"
